iai-group/MovieBot

.pylintrc, doc/source/api/dialogue_manager.rst, doc/source/conf.py, moviebot/agent/agent.py, moviebot/controller/controller.py, moviebot/controller/controller_bot.py, moviebot/controller/controller_terminal.py, moviebot/database/database.py, moviebot/dialogue_manager/dialogue_act.py, moviebot/dialogue_manager/dialogue_context.py, moviebot/dialogue_manager/dialogue_manager.py, moviebot/dialogue_manager/dialogue_policy.py, moviebot/dialogue_manager/dialogue_state.py, moviebot/dialogue_manager/dialogue_state_tracker.py, moviebot/dialogue_manager/item_constraint.py, moviebot/dialogue_manager/operator.py, moviebot/dialogue_manager/values.py, moviebot/intents/agent_intents.py, moviebot/nlg/nlg.py, moviebot/nlu/data_loader.py, moviebot/nlu/nlu.py, moviebot/nlu/slot_annotator.py, moviebot/nlu/user_intents_checker.py, moviebot/ontology/ontology.py, moviebot/recorder/dialogue_recorder.py, moviebot/recorder/recorder_bot.py, run_bot.py
fixes #3 
In addition, I fixed many long lines with ypaf auto formatter as suggested in https://google.github.io/styleguide/pyguide.html.
=> Google docstrings

CONTRIBUTING.md, doc/source/index.rst, doc/source/installation.rst, doc/source/usage.rst
=> Added CONTRIBUTING.md to the project

CONTRIBUTING.md, doc/source/api/agent.rst, doc/source/api/controller.rst, doc/source/api/main.rst, doc/source/api/nlu.annotators.rst, doc/source/api/nlu.intent_checker.rst, doc/source/api/nlu.rst, doc/source/index.rst, doc/source/installation.rst, doc/source/usage.rst, moviebot/controller/controller.py, moviebot/dialogue_manager/item_constraint.py, moviebot/intents/user_intents.py, moviebot/nlu/nlu.py, moviebot/nlu/rule_based_annotator.py, moviebot/nlu/slot_annotator.py, moviebot/nlu/user_intents_checker.py, moviebot/ontology/ontology.py
This fixes #9.
Documentation was updated to reflect the new changes. In addition I made some modifications to the documentation to better reflect the project as described in [IAI MovieBot](https://arxiv.org/abs/2009.03668).
=> SlotAnnotator as abstract class

doc/source/api/main.rst, doc/source/api/utterance.rst, moviebot/nlu/text_processing.py, moviebot/utterance/utterance.py, moviebot/utterance/utterance_agent.py, moviebot/utterance/utterance_user.py, tests/nlu/test_text_processing.py, tests/utterance/test_utterance_user.py
=> created the utterance classes

moviebot/dialogue_manager/dialogue_act.py, moviebot/nlg/nlg.py, moviebot/nlu/annotation/item_constraint.py, moviebot/nlu/annotation/rule_based_annotator.py, moviebot/nlu/annotation/semantic_annotation.py, moviebot/nlu/annotation/slots.py, moviebot/nlu/annotation/values.py, moviebot/nlu/text_processing.py, moviebot/nlu/user_intents_checker.py
closes #25 
Had to make bigger adjustments in genres and year annotators.
=> Feature - add semntic annotation to item constraint

moviebot/nlu/annotation/rule_based_annotator.py, moviebot/nlu/annotation/semantic_annotation.py, moviebot/nlu/text_processing.py, moviebot/nlu/user_intents_checker.py, moviebot/utterance/utterance.py, tests/nlu/test_text_processing.py
Closes #33 
I have also renamed TextProcess class to Tokenizer since the main goal of the class is to create and return tokens.
=> Implement Span Class

moviebot/controller/controller_telegram.py
=> Provide user id to the user

.flake8, .github/workflows/build.yaml, .github/workflows/merge.yaml, .pre-commit-config.yaml, README.md, pyproject.toml, requirements.txt, tests/utterance/test_utterance_user.py
Fixes #54 
Note: Tests are failing at the moment but fixes for those are not a part of this PR.
=> Add pre-commit hooks and github actions

.github/workflows/build.yaml, .github/workflows/merge.yaml
=> Add NLTK downloads.

moviebot/controller/controller.py, moviebot/controller/controller_terminal.py
=> Restart functionality is broken in cmd line version

docs/source/installation.rst
=> Clean up Messenger related documentation

docs/source/conf.py, eval/evaluation.py, moviebot/agent/agent.py, moviebot/controller/controller_messenger.py, moviebot/controller/controller_telegram.py, moviebot/core/shared/intents/agent_intents.py, moviebot/core/shared/intents/user_intents.py, moviebot/core/shared/utterance/utterance.py, moviebot/database/database.py, moviebot/dialogue_manager/dialogue_act.py, moviebot/dialogue_manager/dialogue_context.py, moviebot/dialogue_manager/dialogue_manager.py, moviebot/dialogue_manager/dialogue_policy.py, moviebot/dialogue_manager/dialogue_state.py, moviebot/dialogue_manager/dialogue_state_tracker.py, moviebot/nlg/nlg.py, moviebot/nlu/annotation/item_constraint.py, moviebot/nlu/annotation/operator.py, moviebot/nlu/annotation/rule_based_annotator.py, moviebot/nlu/annotation/semantic_annotation.py, moviebot/nlu/annotation/slot_annotator.py, moviebot/nlu/annotation/slots.py, moviebot/nlu/annotation/values.py, moviebot/nlu/data_loader.py, moviebot/nlu/nlu.py, moviebot/nlu/text_processing.py, moviebot/ontology/ontology.py, moviebot/recorder/dialogue_recorder.py, moviebot/recorder/recorder_bot.py, tests/nlu/test_text_processing.py
Fixes #84
Runs Black on all files to make future PRs cleaner.
=> run black on all files

moviebot/nlu/user_intents_checker.py, tests/mocks/mock_ontology.py, tests/nlu/test_user_intents_checker.py
=> Fix self.ontology to be class Ontology

moviebot/nlu/annotation/rule_based_annotator.py, tests/nlu/test_rule_based_annotator.py
Fixes #46 
Only the last function in rule_based_annotator.py was modified. The remaining changes are related to black.
=> Fix utterance parsing + tests

requirements.txt
=> Add questionary to requirements.txt

moviebot/ontology/ontology.py
Format docstrings in ontology module
Fixes #95
=> Format docstrings in ontology module

eval/evaluation.py, moviebot/agent/agent.py, moviebot/controller/controller.py, moviebot/controller/controller_telegram.py, moviebot/dialogue_manager/dialogue_state.py
=> Fix docstrings, typing and string construction - agent

moviebot/database/database.py
=> Fix docstrings, typing and string construction - database

moviebot/core/utterance/utterance.py
=> Fix docstrings, typing and string construction - core

moviebot/controller/controller_terminal.py
=> Fix option prsentation in terminal when option not a list

moviebot/dialogue_manager/dialogue_act.py, moviebot/dialogue_manager/dialogue_context.py, moviebot/dialogue_manager/dialogue_manager.py, moviebot/dialogue_manager/dialogue_policy.py, moviebot/dialogue_manager/dialogue_state.py, moviebot/dialogue_manager/dialogue_state_tracker.py
=> Fix docstrings, typing and string construction - DM

moviebot/dialogue_manager/dialogue_act.py, moviebot/nlu/annotation/item_constraint.py, moviebot/nlu/annotation/operator.py, moviebot/nlu/annotation/rule_based_annotator.py, moviebot/nlu/annotation/semantic_annotation.py, moviebot/nlu/data_loader.py, moviebot/nlu/nlu.py, moviebot/nlu/text_processing.py, moviebot/nlu/user_intents_checker.py, tests/mocks/mock_data_loader.py
=> Fix docstrings, typing and string construction - nlu

requirements.txt, scripts/telegram_health_check.sh
- Add script to ensure Telegram bot is still running
- Set `python-telegram-bot` version to 13.15 for compatibility reasons
=> Start Telegram on gustav1

moviebot/controller/http_data_formatter.py
=> Add messenger formatter to format data to HTTP object

moviebot/controller/controller.py, moviebot/controller/controller_flask.py
=> Flask controller

tests/utterance/test_utterance_user.py
=> Add tests for core

moviebot/nlu/annotation/item_constraint.py, moviebot/nlu/annotation/rule_based_annotator.py, tests/nlu/test_rule_based_annotator.py
=> Increase test coverage for NLU module

moviebot/recommender/recommender_model.py, moviebot/recommender/slot_based_recommender_model.py
Creates a recommender module with an abstract class and a subclass for slot-based recommendation.
Upon approval, the recommendation process in `DialogueManager` should be refactored and tests should be added (issue #145).
Part of #49
=> Add recommender module

moviebot/controller/server_socket.py
=> Align socket server with the updated controller

config/moviebot_config.yaml, moviebot/run.py, requirements.txt
=> Add argparse and confuse

config/moviebot_config.yaml, config/moviebot_config_no_integration.yaml, moviebot/agent/agent.py, moviebot/dialogue_manager/dialogue_manager.py, moviebot/dialogue_manager/dialogue_policy.py, tests/dialogue_manager/test_dialogue_manager.py, tests/dialogue_manager/test_dialogue_policy.py
=> Factor out recommender model

moviebot/controller/controller.py, moviebot/controller/controller_telegram.py
=> Fix docstrings, typing and string construction - controller

moviebot/controller/http_data_formatter.py
Update the message when a recommendation is made. 
Fixes #169
=> Fix flow where a new recommendation is made inappropriately

README.md, moviebot/controller/controller_flask.py, moviebot/controller/http_data_formatter.py
=> Fix attachments in Flask server messages

docs/source/usage.rst
Add documentation on how to run MovieBot with Flask. It is based on the modifications done in PR #175.
Fixes #155
=> Add documentation for Flask deployment

.github/workflows/build.yaml, eval/evaluation.py, moviebot/agent/agent.py, moviebot/controller/controller.py, moviebot/controller/controller_flask.py, moviebot/controller/controller_telegram.py, moviebot/controller/controller_terminal.py, moviebot/core/intents/agent_intents.py, moviebot/core/intents/user_intents.py, moviebot/core/utterance/utterance.py, moviebot/dialogue_manager/dialogue_context.py, moviebot/nlg/nlg.py, moviebot/nlu/nlu.py, moviebot/nlu/user_intents_checker.py, requirements.txt, tests/nlu/test_rule_based_annotator.py, tests/nlu/test_user_intents_checker.py, tests/utterance/test_utterance_user.py
- Remove `Utterance` and `AgentUtterance` class
- `UserUtterance` inherits from DialogueKit `Utterance`
- Refactor `UserIntents` and `AgentIntents` to use DialogueKit `Intent`
- Fix related tests
Fixes #166
=> Refactor core packages to use DialogueKit

moviebot/nlg/nlg.py
=> Fix NLG error

README.md
=> Update Telegram link in README

moviebot/core/utterance/utterance.py, reinforcement_learning/environment/__init__.py, reinforcement_learning/environment/dialogue_env_moviebot.py, reinforcement_learning/environment/dialogue_env_moviebot_no_nlu.py
This PR updates the registration of Gymnasium environment as per package documentation. And update method names based on PR #216.
=> Update env based on RL agent

reinforcement_learning/README.md
Add information for training dialogue policy via reinforcement learning.
Fixes #224
=> Add documentation for RL

README.md, docs/source/architecture.rst, moviebot/nlu/annotation/joint_bert/joint_bert_train.py
=> Add documentation for NLU training
